/* Each new term in the Fibonacci sequence is generated by adding 
 * the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed 
 * four million, find the sum of the even-valued terms. */

#include <stdio.h>

int main (void)
{
    int sum=0;
    int val;
    int n1=0;
    int n2=1;
    int count=0;
    
    while (n2 <= 4000000)
    {
        val = n1+n2;
        n1 = n2;
        n2 = val;
        if ((val%2) == 0)
            sum += val;
    }

    printf("The sum is %d\n", sum);
               return 0;
}
